name: AWS Heartbeat
run-name: ${{ github.actor }} triggered AWS Heartbeat

# This whole workflow is not actually required from a functional perspective. Howeever, GitHub tends to unregister
# runners if they are inactive for a month. So this workflow ensures our runner is activated once a week and 
# GitHub does not unregister it.

#Set Triggers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 3'
  
#Jobs  
jobs:
  start-instance:
    runs-on: ubuntu-latest
    steps:
      #General Setup
      - name: Checkout actions
        uses: actions/checkout@v4
      #Start AWS Instance
      - name: Start Instance
        uses: ./.github/actions/start-aws-instance
        with:
          region: eu-central-1
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_access_key_id: ${{ secrets.AWS_KEY }}
          aws_build_ami_id: ${{ vars.AWS_BUILD_AMI_ID }}
          aws_instance_type: ${{ vars.AWS_INSTANCE_TYPE }}

  # This task is not actually required. It's only there to make sure GitHub logs that the runner
  # .. took a job
  dummy-job:
    runs-on: [self-hosted, aws]
    needs: start-instance
    steps:
      # Print System Time
      - name: Print System Time
        run: |
          date


  # Stopping the instance is not required (it stops automatically
  # when it is unused for some time, controlled by AWS alarm)